name: Quality

on:
  push:
    branches:
      - main
      - chore/**
      - fix/**
      - feat/**

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup component add rustfmt

      - name: Toolchain info
        run: |
          cargo --version
          rustc --version
          cargo fmt --version
          cargo clippy --version

      - name: Lint
        run: |
          cd src
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cargo build --release