name: Publish

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup component add rustfmt
      - name: Toolchain info
        run: |
          cargo --version
          rustc --version
          cargo fmt --version
          cargo clippy --version
      - name: Lint
        run: |
          cd src
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Test
        run: |
          cargo check
          cargo test --all          

  need_publish:
    runs-on: ubuntu-latest
    needs: run_tests
    outputs:
      is_bumped: ${{ steps.npm_check.outputs.changes }}
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - id: npm_check
        shell: bash
        run: |
          manifest=$(jq -r '.version' ./npm/robespierre/package.json)
          npm=$(npm view robespierre --json | jq -r '.version')
          [[ "$manifest" == "$npm" ]] && echo "false" >> "$GITHUB_OUTPUT" || echo "true" >> "$GITHUB_OUTPUT"

  publish-npm-binaries:
    name: Publish NPM packages
    needs: need_publish
    if: needs.need_publish.outputs.is_bumped == 'true'
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - {
            NAME: linux-x64-glibc,
            OS: ubuntu-20.04,
            TARGET: x86_64-unknown-linux-gnu,
          }
          - {
            NAME: linux-arm64-glibc,
            OS: ubuntu-20.04,
            TARGET: aarch64-unknown-linux-gnu,
          }
          - {
            NAME: win32-x64-msvc,
            OS: windows-2022,
            TARGET: x86_64-pc-windows-msvc,
          }
          - {
            NAME: win32-arm64-msvc,
            OS: windows-2022,
            TARGET: aarch64-pc-windows-msvc,
          }
          - {
            NAME: darwin-x64,
            OS: macos-11,
            TARGET: x86_64-apple-darwin,
          }
          - {
            NAME: darwin-arm64,
            OS: macos-11,
            TARGET: aarch64-apple-darwin,
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set the release version
        shell: bash
        run: |
          export RELEASE_VERSION=${GITHUB_REF:11}
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.build.TOOLCHAIN }}
          target: ${{ matrix.build.TARGET }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target ${{ matrix.build.TARGET }}
          use-cross: ${{ matrix.build.OS == 'ubuntu-20.04' }} # use `cross` for Linux builds

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to NPM
        shell: bash
        run: sh ./package.sh --publish
        env:
          BUILD_NAME: ${{ matrix.build.NAME }}
          BUILD_OS: ${{ matrix.build.OS }}
          BUILD_TARGET: ${{ matrix.build.TARGET }}
          BUILD_VERSION: ${{ env.RELEASE_VERSION }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-npm-base:
    name: Publish the base NPM package
    needs: publish-npm-binaries
    if: needs.need_publish.outputs.is_bumped == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Publish the package
        shell: bash
        run: |
          cd npm/robespierre
          npm i
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
